process.stdout;
process.stdout.write;
var assert;
assert.deepEqual;
assert.equal;
assert.fail;
fs.existsSync = function(name) { };
fs.closeSync = function(name) { };
fs.readdirSync = function(name) { };
fs.lstatSync = function(name) { };
var fd;
