* Numbers
** Number to words
Functionality in mathspeak_util
*** Ordinals 
*** vulgar fractions
**** Spanish: Above 10 denominator no longer ordinals.
**** Maybe just have X entre Y
**** 

*** Mixed numbers 
    Maybe a shorter version in brief/sbrief

** Decimal points

Make this a grammar postprocessor

** Large number seperators

Same grammar postprocessor as above

** Parentheses

Changed everywhere (  cierra ) to left and right: izquierdo, derecho

** Begin and End of font styles? 
   
*** There are no tests. Do they work?

* Fractions
Functionality in mathspeak_util


* Sub and superscript nesting
Functionality in mathspeak_util

* Font names

Semantic post-processor

* Abstraction and Prefix rules!

* Language specific:

** Spanish:

*** Replaces mas by más in tests (meaning plus)

**** DONE Ask Oscar if that is correct! 

**** Correct


*** mayúscula 

**** Is it after a letter or before?

     Currently I have rewritten A -> mayúscula A in MP.
     Check all the rules.

*** Ye vs Y

**** What is correct?

**** They have not yet been capitalised!

**** Let's stay with Y

**** TODO Change in symbols file.

**** Cleanup spanish.js symbols

***** spanishMP are names extracted from MathPlayer unicode rules that have been overwritten with Oscar's alternatives.

      "spanish": "aproximado",   <<<< 
      "spanishMP": "casi igual a"

      "spanish": "almuhadilla",
      "spanishMP": "signo de número"


**** Create units and functions

*** Test:

**** Nested roots all seem to be 


*** Finalise:
    Questions for Oscar.

**** Check 121 with bajobajo vs single bajo

**** Check 104-117 in brief and superbrief with mod inferior/mod superior.

**** Box around an expression is: StartEnclose EndEnclose. What is the Spanish equivalent.

**** Label for multi line equations: etiqueta


